### ISSUE TITLE
Change link from arti01to artifactory

### ISSUE THREAD

**Issue by mreynier** [Coppernic/Serial#6]

**Comment by gintasz** [comment]
Having problem with this too. Trying latest source present at this time.

![image](https://user-images.githubusercontent.com/6189625/83637667-a5a36f00-a5b0-11ea-83ea-830993b53db0.png)


If I comment out arti01 repositories, then some kind of "git pull" hangs forever.
![image](https://user-images.githubusercontent.com/6189625/83636449-ac30e700-a5ae-11ea-96b0-5c5db3554b71.png)
